name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build-go:
    name: Go Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21', '1.22']
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5.0.1
      with:
        go-version: ${{ matrix.go }}

    - name: Go Build dcrdata
      run: go build -v ./...
      working-directory: ./cmd/dcrdata

    - name: Install Linters
      run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1"

    - name: Go Tests
      run: |
        ./run_tests.sh

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm clean-install
        run: npm clean-install
        working-directory: ./cmd/dcrdata

      - name: npm run build
        run: |
          npm run build
          git diff --exit-code views/extras.tmpl
        working-directory: ./cmd/dcrdata
