name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build-go:
    name: Go Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.25']
    steps:
    - name: Check out source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ matrix.go }}
    - name: Use lint cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/.cache/golangci-lint
        key: go-lint-${{ matrix.go }}-${{ hashFiles('./go.sum') }}
        restore-keys: go-lint-${{ matrix.go }}
    - name: Install Linters
      run: "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0"
    - name: Go Build dcrdata
      run: go build -v ./...
      working-directory: ./cmd/dcrdata
    - name: Go Tests
      run: |
        ./run_tests.sh

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 #v5.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm clean-install
        run: npm clean-install
        working-directory: ./cmd/dcrdata

      - name: npm run build
        run: |
          npm run build
          git diff --exit-code views/extras.tmpl
        working-directory: ./cmd/dcrdata
